# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for GitHub Actions
  # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
    # Make sure we don't just pull in freshly released versions
    cooldown:
      default-days: 14
      exclude:
        - "myst-cli"
    groups:
      npm:
        patterns: ["*"]
    labels:
      - "maintenance"
      - "javascript"
      - "dependencies"

  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for a `pyproject.toml` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    groups:
      pip:
        patterns: ["*"]
    labels:
      - "maintenance"
      - "python"
      - "dependencies"
