# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      docs/conf\.py|
      tests/test_tocdirective/.*|
      tests/test_sphinx_jupyterbook_latex/.*|
    )$

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: local
    hooks:
    - id: check-doc-req
      name: Check .binder/requirements.txt up-to-date
      pass_filenames: false
      additional_dependencies:
      - tomli
      files: >-
          (?x)^(
              pyproject.toml|
              .binder/requirements.txt|
              scripts/check_doc_requirements.py|
          )$
      language: python
      language_version: python3
      entry: python scripts/check_doc_requirements.py

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
    - id: ruff
      args: ["--fix", "--show-fixes"]
    - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      # Allow inline ignores for spelling lines
      args: ["--ignore-regex", "^.{1024}|^.*\\!ignore-spelling|RePEc:the:publsh:1367"]
      exclude: >
        (?x)^(
            tests/.*|
            .*\.bib|
            CHANGELOG.md
        )$
