#######################################################################################
# Jekyll site settings
title: YOUR BOOK NAME
author: YOUR AUTHOR NAME
email: YOUR EMAIL

baseurl: "/" # the subpath of your site, e.g. /blog. If there is no subpath for your site, use an empty string ""
url: "YOUR URL" # the base hostname & protocol for your site, e.g. http://example.com

textbook_logo_link        : https://jupyter.org/jupyter-book/  # A link for the logo.

#######################################################################################
# Interact link settings

# General interact settings
use_jupyterlab                   : false  # If 'true', interact links will use JupyterLab as the interface

# Jupyterhub link settings
use_jupyterhub_button            : false  # If 'true', display a button that will direct users to a JupyterHub (that you provide)

# Binder link settings
use_binder_button                : false  # If 'true', add a binder button for interactive links
binder_repo_org                  : "YOUR-ORG"  # The username or organization that owns this repository
binder_repo_name                 : "YOUR-REPO"  # The name of the repository on the web
