name: build-deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - utf8
  pull_request:
    branches:
    - utf8

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # Set up Miniconda with environment
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.1.2
      with:
        environment-file: windows_tests/environment.yml
        activate-environment: buildit
        python-version: 3.7
        auto-activate-base: false

    # Build the book
    - name: Build the book
      shell: bash -l {0}
      run: |
        pip install -e . --upgrade
        ORIG_DIR="${PWD}"
        mkdir -p html_out
        cd windows_tests/quantecon_flat/mini_book
        jupyter-book build docs
        echo "changing to ${ORIG_DIR}/html_out/flat_test"
        cp -a docs/_build/html "${ORIG_DIR}/html_out/flat_test"
        cd "${ORIG_DIR}/html_out/flat_test"
        echo "now in ${CWD}"
        ls -lrtd *


    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.10
      if: matrix.os == 'windows-latest' && github.event_name == 'push'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html_out
